import type { Faq, Paquete, Propiedad, Testimonio } from "./types";

export const PROPIEDADES_INICIALES: Propiedad[] = [
  {
    id: "M2-3407",
    titulo: "Residencia Premium con Costa de Lago",
    ubicacion: "Villa Carlos Paz, Córdoba",
    precio: "USD 1.150.000",
    precioValor: 1150000,
    monedaPrecio: "USD",
    operacion: "Venta",
    tipo: "Casa de Lujo",
    m2Totales: 850,
    m2Cubiertos: 520,
    ambientes: 6,
    dormitorios: 4,
    banos: 5,
    cocheras: 3,
    antiguedad: "A estrenar",
    descripcion:
      "Espectacular propiedad de diseño contemporáneo ubicada sobre la costa del lago. Cuenta con amplios ventanales de doble vidrio (DVH), muelle privado, piscina climatizada sin fin con vista panorámica, quincho equipado de alto nivel y terminaciones en piedra y madera noble.",
    origen: "ZonaProp",
    visitas: 124,
    estado: "Activa",
    agenteId: "u_admin",
    destacada: true,
    lat: -31.4241,
    lng: -64.4978,
    fechaAlta: "2026-06-14",
    imagenes: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "M2-3408",
    titulo: "Departamento 2 Dormitorios c/ Balcón Terraza",
    ubicacion: "Nueva Córdoba, Córdoba",
    precio: "USD 135.000",
    precioValor: 135000,
    monedaPrecio: "USD",
    operacion: "Venta",
    tipo: "Departamento",
    m2Totales: 85,
    m2Cubiertos: 72,
    ambientes: 3,
    dormitorios: 2,
    banos: 2,
    cocheras: 1,
    antiguedad: "2 años",
    descripcion:
      "Luminoso departamento ubicado en el corazón de Nueva Córdoba. Cuenta con cocina semiintegrada con amoblamiento de primera calidad, amplio estar comedor, balcón con asador propio y suite principal con vestidor.",
    origen: "ZonaProp",
    visitas: 98,
    estado: "Activa",
    agenteId: "u_pro",
    lat: -31.4293,
    lng: -64.1811,
    fechaAlta: "2026-07-02",
    imagenes: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "M2-3409",
    titulo: "Oficina Corporativa de Categoría en Torre Premium",
    ubicacion: "Colectora Av. Luchesse, Villa Allende",
    precio: "$ 850.000 /mes",
    precioValor: 850000,
    monedaPrecio: "ARS",
    operacion: "Alquiler",
    tipo: "Oficina",
    m2Totales: 120,
    m2Cubiertos: 120,
    ambientes: 4,
    dormitorios: 0,
    banos: 2,
    cocheras: 2,
    antiguedad: "1 año",
    descripcion:
      "Planta libre corporativa en complejo de oficinas AAA. Incluye sala de reuniones vidriada, kitchenette equipada, climatización central VRV, control de acceso biométrico y seguridad 24 hs.",
    origen: "MercadoLibre",
    visitas: 45,
    estado: "Activa",
    agenteId: "u_admin",
    lat: -31.2966,
    lng: -64.3005,
    fechaAlta: "2026-05-20",
    imagenes: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "M2-3410",
    titulo: "Casa de Estilo en Barrio Jardín c/ Gran Parque",
    ubicacion: "Barrio Jardín, Córdoba",
    precio: "$ 1.200.000 /mes",
    precioValor: 1200000,
    monedaPrecio: "ARS",
    operacion: "Alquiler",
    tipo: "Casa",
    m2Totales: 450,
    m2Cubiertos: 280,
    ambientes: 5,
    dormitorios: 3,
    banos: 3,
    cocheras: 2,
    antiguedad: "8 años",
    descripcion:
      "Excelente propiedad familiar en zona residencial tranquila. Desarrollada en dos plantas, cuenta con gran parque verde, piscina, quincho cerrado con asador y dependencias de servicio.",
    origen: "ZonaProp",
    visitas: 112,
    estado: "Activa",
    agenteId: "u_agente",
    lat: -31.4372,
    lng: -64.1922,
    fechaAlta: "2026-06-30",
    imagenes: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "M2-3411",
    titulo: "Semipiso Exclusivo en Zona Bv. Chacabuco",
    ubicacion: "Nueva Córdoba, Córdoba",
    precio: "USD 240.000",
    precioValor: 240000,
    monedaPrecio: "USD",
    operacion: "Venta",
    tipo: "Departamento",
    m2Totales: 160,
    m2Cubiertos: 145,
    ambientes: 4,
    dormitorios: 3,
    banos: 3,
    cocheras: 1,
    antiguedad: "A estrenar",
    descripcion:
      "Semipiso de categoría con vista panorámica al bulevar. Calefacción por radiadores, aberturas de aluminio con DVH, pisos de porcelanato de gran formato y terminaciones de lujo.",
    origen: "ZonaProp",
    visitas: 156,
    estado: "Activa",
    agenteId: "u_pro",
    destacada: true,
    lat: -31.4295,
    lng: -64.1859,
    fechaAlta: "2026-07-18",
    imagenes: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "M2-3412",
    titulo: "Oficina / Consultorio c/ Recepción en Alberdi",
    ubicacion: "Barrio Alberdi, Córdoba",
    precio: "$ 380.000 /mes",
    precioValor: 380000,
    monedaPrecio: "ARS",
    operacion: "Alquiler",
    tipo: "Oficina",
    m2Totales: 50,
    m2Cubiertos: 50,
    ambientes: 2,
    dormitorios: 0,
    banos: 1,
    cocheras: 0,
    antiguedad: "5 años",
    descripcion:
      "Funcional oficina comercial apta para profesionales o consultorios médicos. Dispone de área de recepción, privado independiente, baño privado y aire acondicionado instalado.",
    origen: "MercadoLibre",
    visitas: 32,
    estado: "Activa",
    agenteId: "u_agente",
    lat: -31.4144,
    lng: -64.1955,
    fechaAlta: "2026-05-12",
    imagenes: [
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "M2-3413",
    titulo: "PH tipo Casa 3 Amb con Patio",
    ubicacion: "Alta Córdoba, Córdoba",
    precio: "USD 89.000",
    precioValor: 89000,
    monedaPrecio: "USD",
    operacion: "Venta",
    tipo: "PH",
    m2Totales: 95,
    m2Cubiertos: 78,
    ambientes: 3,
    dormitorios: 2,
    banos: 1,
    cocheras: 0,
    antiguedad: "40 años",
    descripcion:
      "PH al frente con entrada independiente, patio uruguayo con parrilla y lavadero cubierto. Ideal primera vivienda, en zona con excelente conectividad.",
    origen: "ZonaProp",
    visitas: 71,
    estado: "Activa",
    agenteId: "u_admin",
    lat: -31.3966,
    lng: -64.1817,
    fechaAlta: "2026-04-08",
    imagenes: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "M2-3414",
    titulo: "Loft Industrial con Doble Altura",
    ubicacion: "Güemes, Córdoba",
    precio: "USD 175.000",
    precioValor: 175000,
    monedaPrecio: "USD",
    operacion: "Venta",
    tipo: "Loft",
    m2Totales: 68,
    m2Cubiertos: 68,
    ambientes: 2,
    dormitorios: 1,
    banos: 1,
    cocheras: 1,
    antiguedad: "3 años",
    descripcion:
      "Loft de diseño en pleno paseo de Güemes. Doble altura, vigas de hierro a la vista, cocina isla y suite en entrepiso. Amenities: rooftop con pileta y solarium.",
    origen: "ZonaProp",
    visitas: 143,
    estado: "Activa",
    agenteId: "u_pro",
    destacada: true,
    lat: -31.4266,
    lng: -64.1936,
    fechaAlta: "2026-07-25",
    imagenes: [
      "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "M2-3415",
    titulo: "Quinta con Casa Principal y Pileta",
    ubicacion: "Villa Warcalde, Córdoba",
    precio: "USD 320.000",
    precioValor: 320000,
    monedaPrecio: "USD",
    operacion: "Venta",
    tipo: "Quinta",
    m2Totales: 2200,
    m2Cubiertos: 240,
    ambientes: 5,
    dormitorios: 3,
    banos: 2,
    cocheras: 4,
    antiguedad: "15 años",
    descripcion:
      "Quinta de 2.200 m² con casa principal de estilo colonial, gran galería perimetral, pileta de 10x4, quincho cerrado y arboleda añosa. Perforación propia.",
    origen: "MercadoLibre",
    visitas: 89,
    estado: "Activa",
    agenteId: "u_admin",
    lat: -31.3244,
    lng: -64.2811,
    fechaAlta: "2026-06-01",
    imagenes: [
      "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "M2-3416",
    titulo: "Terreno Countries Estancia Q2",
    ubicacion: "La Calera, Córdoba",
    precio: "USD 95.000",
    precioValor: 95000,
    monedaPrecio: "USD",
    operacion: "Venta",
    tipo: "Terreno",
    m2Totales: 1100,
    m2Cubiertos: 0,
    ambientes: 0,
    dormitorios: 0,
    banos: 0,
    cocheras: 0,
    antiguedad: "—",
    descripcion:
      "Lote en country premium con todos los servicios: agua, cloacas, gas natural, fibra óptica. Vista abierta a las sierras. Reglamento con permite construir hasta 400 m².",
    origen: "ZonaProp",
    visitas: 54,
    estado: "Activa",
    agenteId: "u_pro",
    lat: -31.3477,
    lng: -64.3428,
    fechaAlta: "2026-05-15",
    imagenes: [
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "M2-3417",
    titulo: "Monoambiente Amoblado en Torre con Amenities",
    ubicacion: "General Paz, Córdoba",
    precio: "$ 320.000 /mes",
    precioValor: 320000,
    monedaPrecio: "ARS",
    operacion: "Alquiler",
    tipo: "Departamento",
    m2Totales: 38,
    m2Cubiertos: 35,
    ambientes: 1,
    dormitorios: 1,
    banos: 1,
    cocheras: 0,
    antiguedad: "4 años",
    descripcion:
      "Monoambiente totalmente amoblado y equipado. Torre con laundry, gimnasio, SUM y pileta. Ideal profesional o estudiante. Cochera opcional con costo adicional.",
    origen: "ZonaProp",
    visitas: 187,
    estado: "Activa",
    agenteId: "u_agente",
    lat: -31.4144,
    lng: -64.1706,
    fechaAlta: "2026-07-30",
    imagenes: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?auto=format&fit=crop&w=1200&q=80",
    ],
  },
  {
    id: "M2-3418",
    titulo: "Local Comercial Esquina Alto Tránsito",
    ubicacion: "Cerro de las Rosas, Córdoba",
    precio: "USD 195.000",
    precioValor: 195000,
    monedaPrecio: "USD",
    operacion: "Venta",
    tipo: "Local",
    m2Totales: 82,
    m2Cubiertos: 82,
    ambientes: 2,
    dormitorios: 0,
    banos: 1,
    cocheras: 0,
    antiguedad: "12 años",
    descripcion:
      "Local comercial en esquina de alto tránsito peatonal y vehicular. Frente vidriado sobre dos calles, depósito, baño y ambiente principal. Habilitación municipal al día.",
    origen: "MercadoLibre",
    visitas: 62,
    estado: "Activa",
    agenteId: "u_admin",
    lat: -31.3822,
    lng: -64.2261,
    fechaAlta: "2026-04-22",
    imagenes: [
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
    ],
  },
];

export const PAQUETES: Paquete[] = [
  {
    nombre: "Inicial",
    precio: "$8.000",
    propiedades: 15,
    destacado: false,
    beneficios: [
      "15 propiedades con tu marca",
      "Tu foto y WhatsApp en cada ficha",
      "Link personalizado para compartir",
      "Entrega en 24-48 horas",
      "Ideal para probar el servicio",
    ],
  },
  {
    nombre: "Profesional",
    precio: "$15.000",
    propiedades: 30,
    destacado: true,
    beneficios: [
      "30 propiedades con tu marca",
      "Tu foto y WhatsApp en cada ficha",
      "Link personalizado para compartir",
      "Entrega prioritaria (24 hs)",
      "1 modificación incluida sin cargo",
      "Soporte por WhatsApp",
    ],
  },
  {
    nombre: "Oficina",
    precio: "$35.000",
    propiedades: 50,
    destacado: false,
    beneficios: [
      "50 propiedades con tu marca",
      "Tu foto y WhatsApp en cada ficha",
      "Link personalizado para compartir",
      "Entrega prioritaria (24 hs)",
      "3 modificaciones incluidas",
      "Soporte prioritario",
      "Ideal para equipos de ventas",
    ],
  },
];

export const FAQS: Faq[] = [
  {
    pregunta: "¿Cómo funciona el servicio?",
    respuesta:
      "Me pasás los links de ZonaProp o MercadoLibre de las propiedades que querés publicar. Yo te devuelvo fichas web con TU foto, TU WhatsApp y TU marca. Vos copiás ese link y lo pegás en tus publicaciones.",
  },
  {
    pregunta: "¿Por qué necesito esto si ya publico en ZonaProp?",
    respuesta:
      "Cuando un cliente ve tu publicación en ZonaProp y hace clic en 'ver más', termina en la página de la inmobiliaria dueña de la publicación, no en la tuya. Con mis fichas, el cliente siempre te contacta a VOS.",
  },
  {
    pregunta: "¿Cuánto tarda la entrega?",
    respuesta:
      "El paquete Inicial se entrega en 24-48 horas. Los paquetes Profesional y Oficina tienen entrega prioritaria en 24 horas.",
  },
  {
    pregunta: "¿Puedo modificar una ficha después?",
    respuesta:
      "El paquete Profesional incluye 1 modificación sin cargo y el Oficina incluye 3. Modificaciones adicionales tienen un costo mínimo que acordamos por WhatsApp.",
  },
  {
    pregunta: "¿Las fichas tienen vencimiento?",
    respuesta:
      "No. Una vez que te entrego el link, es tuyo para siempre. Podés usarlo en WhatsApp, Instagram, Facebook o donde quieras.",
  },
  {
    pregunta: "¿Cómo pago?",
    respuesta:
      "Transferencia bancaria o MercadoPago. Te paso los datos cuando confirmes el paquete por WhatsApp.",
  },
];

export const TESTIMONIOS: Testimonio[] = [
  {
    id: "t1",
    nombre: "Laura Fernández",
    cargo: "Agente Independiente",
    inmobiliaria: "Fernández Propiedades",
    fotoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80",
    texto:
      "Desde que uso M2Prop dejé de perder clientes en ZonaProp. Los prospectos me contactan a mí directo por WhatsApp. Cerré 4 operaciones en dos meses gracias a las fichas.",
    rating: 5,
  },
  {
    id: "t2",
    nombre: "Martín Ruiz",
    cargo: "Corredor Inmobiliario",
    inmobiliaria: "Ruiz Inmobiliaria",
    fotoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
    texto:
      "La primera vez pensé que era caro, pero la primera venta me pagó el paquete de todo el año. Además la ficha se ve muchísimo mejor que las de las inmobiliarias grandes.",
    rating: 5,
  },
  {
    id: "t3",
    nombre: "Carla Vega",
    cargo: "Asesora Senior",
    inmobiliaria: "Vega Bienes Raíces",
    fotoUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80",
    texto:
      "Le mando el link por WhatsApp a los clientes y me dicen 'qué buena página tenés'. Da otra imagen. Y el proceso de entrega es rapidísimo.",
    rating: 5,
  },
  {
    id: "t4",
    nombre: "Federico Ibáñez",
    cargo: "Broker",
    inmobiliaria: "Ibáñez & Asoc.",
    fotoUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80",
    texto:
      "Tengo equipo de 3 agentes y cada uno tiene su micrositio propio. Los podemos compartir por Instagram y quedan impecables. Simple y directo.",
    rating: 5,
  },
];
